CREATE TABLE EPISODE_LIST(
	SID 		VARCHAR(255)	NOT NULL,
	EPINUM		INT(11)			NOT NULL DEFAULT '0',
	AIR			VARCHAR(255)	NOT NULL DEFAULT '',
	QUALITY		VARCHAR(255)	NOT NULL DEFAULT '',
	FFIND     	TINYINT(3)      NOT NULL DEFAULT '0',
	FDOWN		TINYINT(3)      NOT NULL DEFAULT '0',
	FCOMP		TINYINT(3)      NOT NULL DEFAULT '0',
	FDEL		TINYINT(3)      NOT NULL DEFAULT '0',
	MAGNET		VARCHAR(255)	NOT NULL DEFAULT '',
    HASH     	VARCHAR(255)	NOT NULL DEFAULT '',
    ATIME       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UTIME       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(SID, QUALITY, EPINUM)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;